# Generated by Django 4.2.30 on 2026-05-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(help_text='The URL of the Instagram content to analyze.', max_length=1024)),
                ('analysis_type', models.CharField(choices=[('TEXT', 'Text Analysis'), ('AUDIO', 'Audio Analysis'), ('FRAME', 'Frame Analysis'), ('FULL', 'Full Analysis')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('PROCESSING', 'Processing'), ('ANALYZING', 'Analyzing'), ('GENERATING_REPORT', 'Generating Report'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_phase', models.TextField(blank=True, help_text='Human-readable status updates.')),
                ('error_message', models.TextField(blank=True, help_text='Error details if the job fails.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(default=dict, help_text='The complete structured JSON report output.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FRAME_DIRECTORY', 'Frame Directory'), ('IMAGE', 'Image')], max_length=20)),
                ('file_path', models.CharField(help_text='File path on the local filesystem or storage backend.', max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('processing_status', models.CharField(blank=True, help_text='Status indicating processing state, e.g. NO_AUDIO_FOUND', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Relevant metadata extracted during processing (e.g. video duration, frame count).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='core_app.analysisjob')),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='report',
            field=models.OneToOneField(blank=True, help_text='Associated report generated when job reaches GENERATING_REPORT phase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='core_app.analysisreport'),
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(help_text='The factual assertion detected.')),
                ('detection_source', models.CharField(choices=[('OCR', 'OCR'), ('TRANSCRIPT', 'Transcript'), ('VISUAL', 'Visual')], max_length=20)),
                ('classification_label', models.CharField(choices=[('VERIFIED_LIKELY_TRUE', 'Verified / Likely True'), ('PLAUSIBLE', 'Plausible'), ('UNVERIFIED', 'Unverified'), ('OPINION_OR_SATIRE', 'Opinion or Satire'), ('MISLEADING_CONTEXT', 'Misleading Context'), ('LIKELY_FALSE', 'Likely False'), ('HIGH_RISK', 'High Risk')], max_length=30)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the classification (0.0 to 1.0).')),
                ('contextual_reasoning', models.TextField(help_text='Summary of the contextual reasoning leading to this classification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core_app.analysisjob')),
            ],
            options={
                'indexes': [models.Index(fields=['classification_label'], name='core_app_cl_classif_4c4f18_idx'), models.Index(fields=['detection_source'], name='core_app_cl_detecti_a865d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status'], name='core_app_an_status_ae79cc_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['created_at'], name='core_app_an_created_cb076c_idx'),
        ),
    ]
