# Generated by Django 4.2.30 on 2026-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='ingestion_source',
            field=models.CharField(choices=[('URL', 'Instagram / URL'), ('UPLOAD', 'Local Upload')], default='URL', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename for upload jobs.', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='The URL of the Instagram content to analyze.', max_length=1024, null=True),
        ),
    ]
