# Generated by Django 4.2.30 on 2026-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_upload_ingestion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrecord',
            name='ocr_reference',
            field=models.TextField(blank=True, help_text='Snippet or block from the on-screen OCR text.'),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='transcript_reference',
            field=models.TextField(blank=True, help_text='Snippet or timestamp from the audio transcript.'),
        ),
    ]
