# Generated by Django 4.2.30 on 2026-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_claimrecord_ocr_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FRAME_DIRECTORY', 'Frame Directory'), ('IMAGE', 'Image'), ('THUMBNAIL', 'Thumbnail')], max_length=20),
        ),
    ]
