# Generated by Django 4.2.30 on 2026-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_mediaasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrecord',
            name='related_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of top search results matching this claim.'),
        ),
    ]
